---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: bootstrap-alpine-3.6
    image: alpine:3.6
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_plugins: "/usr/lib/python2.7/site-packages/ara/plugins/callbacks"
    ara:
      database: "sqlite://ara.sqlite"
  lint:
    name: ansible-lint
scenario:
  name: alpine-3.6
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'flake8'
